language: java
jdk: oraclejdk8

install: "./gradlew setupCIWorkspace"
script: "./gradlew build"
after_success: "./gradlew bintrayUpload"

notifications:
  email:
    recipients:
      - lousylynx12@gmail.com
    on_success: never
    on_failure: always